"""add stock_raw_data and stock_analysis_cache

Revision ID: 4e09fb1d0f78
Revises: 78bdc4febc99
Create Date: 2026-03-12 17:13:03.082831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e09fb1d0f78'
down_revision: Union[str, Sequence[str], None] = '78bdc4febc99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_analysis_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('signal_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('action_tag', sa.String(length=20), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_verdict', sa.Text(), nullable=True),
    sa.Column('prev_action_tag', sa.String(length=20), nullable=True),
    sa.Column('prev_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_final', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'record_date', name='uq_cache_symbol_date')
    )
    op.create_index('idx_cache_indicators_gin', 'stock_analysis_cache', ['indicators'], unique=False, postgresql_using='gin')
    op.create_table('stock_raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('technical', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('institutional', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fundamental', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'record_date', name='uq_raw_symbol_date')
    )
    op.create_index('idx_raw_institutional_gin', 'stock_raw_data', ['institutional'], unique=False, postgresql_using='gin')
    op.create_index('idx_raw_technical_gin', 'stock_raw_data', ['technical'], unique=False, postgresql_using='gin')
    op.add_column('daily_analysis_log', sa.Column('is_final', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint(op.f('uq_log_symbol_date'), 'daily_analysis_log', type_='unique')
    op.create_unique_constraint('uq_log_user_symbol_date', 'daily_analysis_log', ['user_id', 'symbol', 'record_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_log_user_symbol_date', 'daily_analysis_log', type_='unique')
    op.create_unique_constraint(op.f('uq_log_symbol_date'), 'daily_analysis_log', ['symbol', 'record_date'], postgresql_nulls_not_distinct=False)
    op.drop_column('daily_analysis_log', 'is_final')
    op.drop_index('idx_raw_technical_gin', table_name='stock_raw_data', postgresql_using='gin')
    op.drop_index('idx_raw_institutional_gin', table_name='stock_raw_data', postgresql_using='gin')
    op.drop_table('stock_raw_data')
    op.drop_index('idx_cache_indicators_gin', table_name='stock_analysis_cache', postgresql_using='gin')
    op.drop_table('stock_analysis_cache')
    # ### end Alembic commands ###
